# Generated by Django 3.2.6 on 2021-08-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='av', to='polls.Author'),
        ),
    ]
