# Generated by Django 3.2.6 on 2021-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_footer_possibilities_services_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_content_feature4',
            field=models.TextField(null=True),
        ),
    ]
