# Generated by Django 3.2.6 on 2021-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_services_services_content_feature4'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='mail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
