# Generated by Django 3.2.6 on 2021-09-04 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietBeTong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KhoiLuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CongViec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenCongViec', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.TextField(max_length=40)),
                ('SoDienThoai', models.CharField(max_length=10)),
                ('DiaChi', models.TextField(max_length=100)),
                ('SoCMT', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.TextField(max_length=40)),
                ('SoDienThoai', models.CharField(max_length=10)),
                ('DiaChi', models.TextField(max_length=100)),
                ('SoCMT', models.TextField(max_length=20)),
                ('congViec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.congviec')),
            ],
        ),
        migrations.CreateModel(
            name='TramTron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenTramTron', models.CharField(max_length=30)),
                ('dungTich', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VatLieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenVatLieu', models.TextField(max_length=50)),
                ('DonVi', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='XeBon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenXe', models.TextField(max_length=40)),
                ('BienSo', models.TextField(max_length=20)),
                ('nhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='MacBetong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenMac', models.TextField(max_length=30)),
                ('DoSut', models.TextField(max_length=20)),
                ('Gia', models.BigIntegerField()),
                ('vatLieu', models.ManyToManyField(through='Quanly.ChiTietBeTong', to='Quanly.VatLieu')),
            ],
        ),
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soKhoi', models.IntegerField()),
                ('tongGia', models.IntegerField()),
                ('ngayTao', models.TimeField(auto_now_add=True)),
                ('ngayDo', models.TimeField()),
                ('trangThai', models.CharField(choices=[('cxl', 'Chua xu li'), ('xl', 'da xu li'), ('dgh', 'da giao hang')], max_length=30)),
                ('khachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.khachhang')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.macbetong')),
                ('tramTron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.tramtron')),
            ],
            managers=[
                ('nvBanhang', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='chitietbetong',
            name='Mac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.macbetong'),
        ),
        migrations.AddField(
            model_name='chitietbetong',
            name='vatlieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanly.vatlieu'),
        ),
        migrations.CreateModel(
            name='CaLamviec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soGio', models.IntegerField()),
                ('caLam', models.CharField(choices=[('S', 'Sang'), ('D', 'Dem')], max_length=5)),
                ('nhanvien', models.ManyToManyField(to='Quanly.NhanVien')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chitietbetong',
            unique_together={('Mac', 'vatlieu')},
        ),
    ]
