# Generated by Django 3.2.6 on 2021-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_content', models.TextField()),
                ('footer_title_tw', models.CharField(max_length=200)),
                ('footer_main_title_tw', models.CharField(max_length=100)),
                ('footer_main1_title_tw', models.CharField(max_length=200)),
                ('footer_content_tw', models.TextField()),
                ('footer_title_into', models.CharField(max_length=200)),
                ('footer_content_into', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkfb', models.CharField(max_length=300)),
                ('linktwitter', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='possibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibilities_title', models.TextField()),
                ('possibilities_main_title', models.CharField(max_length=200)),
                ('possibilities_content', models.TextField()),
                ('possibilities_img1', models.ImageField(null=True, upload_to='')),
                ('possibilities_img2', models.ImageField(null=True, upload_to='')),
                ('possibilities_img3', models.ImageField(null=True, upload_to='')),
                ('possibilities_img4', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_title', models.CharField(max_length=200)),
                ('process_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=200)),
                ('services_main_title', models.CharField(max_length=100)),
                ('services_content', models.TextField()),
                ('services_title_feature1', models.CharField(max_length=200)),
                ('services_content_feature1', models.TextField()),
                ('services_title_feature2', models.CharField(max_length=200)),
                ('services_content_feature2', models.TextField()),
                ('services_title_feature3', models.CharField(max_length=200)),
                ('services_content_feature3', models.TextField()),
                ('services_title_feature4', models.CharField(max_length=200)),
                ('services_content_feature4', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions_title', models.TextField()),
                ('solutions_main_title', models.CharField(max_length=200)),
                ('solutions_content', models.TextField()),
                ('solutions_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('linkfb_team', models.CharField(max_length=300)),
                ('linktwitter_team', models.CharField(max_length=300)),
                ('phone_team', models.CharField(max_length=20)),
                ('image_team', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
