# Generated by Django 3.2.6 on 2021-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0002_remove_donhang_tonggia'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='tongGia',
            field=models.IntegerField(null=True),
        ),
    ]
