# Generated by Django 3.2.6 on 2021-09-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlns', '0003_donhang_tonggia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='tongGia',
        ),
    ]
